/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1PatchTestRequest struct for V202101beta1PatchTestRequest
type V202101beta1PatchTestRequest struct {
	Test *V202101beta1Test `json:"test,omitempty"`
	Mask *string           `json:"mask,omitempty"`
}

// NewV202101beta1PatchTestRequest instantiates a new V202101beta1PatchTestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1PatchTestRequest() *V202101beta1PatchTestRequest {
	this := V202101beta1PatchTestRequest{}
	return &this
}

// NewV202101beta1PatchTestRequestWithDefaults instantiates a new V202101beta1PatchTestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1PatchTestRequestWithDefaults() *V202101beta1PatchTestRequest {
	this := V202101beta1PatchTestRequest{}
	return &this
}

// GetTest returns the Test field value if set, zero value otherwise.
func (o *V202101beta1PatchTestRequest) GetTest() V202101beta1Test {
	if o == nil || o.Test == nil {
		var ret V202101beta1Test
		return ret
	}
	return *o.Test
}

// GetTestOk returns a tuple with the Test field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PatchTestRequest) GetTestOk() (*V202101beta1Test, bool) {
	if o == nil || o.Test == nil {
		return nil, false
	}
	return o.Test, true
}

// HasTest returns a boolean if a field has been set.
func (o *V202101beta1PatchTestRequest) HasTest() bool {
	if o != nil && o.Test != nil {
		return true
	}

	return false
}

// SetTest gets a reference to the given V202101beta1Test and assigns it to the Test field.
func (o *V202101beta1PatchTestRequest) SetTest(v V202101beta1Test) {
	o.Test = &v
}

// GetMask returns the Mask field value if set, zero value otherwise.
func (o *V202101beta1PatchTestRequest) GetMask() string {
	if o == nil || o.Mask == nil {
		var ret string
		return ret
	}
	return *o.Mask
}

// GetMaskOk returns a tuple with the Mask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PatchTestRequest) GetMaskOk() (*string, bool) {
	if o == nil || o.Mask == nil {
		return nil, false
	}
	return o.Mask, true
}

// HasMask returns a boolean if a field has been set.
func (o *V202101beta1PatchTestRequest) HasMask() bool {
	if o != nil && o.Mask != nil {
		return true
	}

	return false
}

// SetMask gets a reference to the given string and assigns it to the Mask field.
func (o *V202101beta1PatchTestRequest) SetMask(v string) {
	o.Mask = &v
}

func (o V202101beta1PatchTestRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Test != nil {
		toSerialize["test"] = o.Test
	}
	if o.Mask != nil {
		toSerialize["mask"] = o.Mask
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1PatchTestRequest struct {
	value *V202101beta1PatchTestRequest
	isSet bool
}

func (v NullableV202101beta1PatchTestRequest) Get() *V202101beta1PatchTestRequest {
	return v.value
}

func (v *NullableV202101beta1PatchTestRequest) Set(val *V202101beta1PatchTestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1PatchTestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1PatchTestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1PatchTestRequest(val *V202101beta1PatchTestRequest) *NullableV202101beta1PatchTestRequest {
	return &NullableV202101beta1PatchTestRequest{value: val, isSet: true}
}

func (v NullableV202101beta1PatchTestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1PatchTestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
