/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1MeshMetric struct for V202101beta1MeshMetric
type V202101beta1MeshMetric struct {
	Name   *string `json:"name,omitempty"`
	Health *string `json:"health,omitempty"`
	Value  *string `json:"value,omitempty"`
}

// NewV202101beta1MeshMetric instantiates a new V202101beta1MeshMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1MeshMetric() *V202101beta1MeshMetric {
	this := V202101beta1MeshMetric{}
	return &this
}

// NewV202101beta1MeshMetricWithDefaults instantiates a new V202101beta1MeshMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1MeshMetricWithDefaults() *V202101beta1MeshMetric {
	this := V202101beta1MeshMetric{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V202101beta1MeshMetric) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshMetric) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V202101beta1MeshMetric) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V202101beta1MeshMetric) SetName(v string) {
	o.Name = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *V202101beta1MeshMetric) GetHealth() string {
	if o == nil || o.Health == nil {
		var ret string
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshMetric) GetHealthOk() (*string, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *V202101beta1MeshMetric) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given string and assigns it to the Health field.
func (o *V202101beta1MeshMetric) SetHealth(v string) {
	o.Health = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V202101beta1MeshMetric) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshMetric) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V202101beta1MeshMetric) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *V202101beta1MeshMetric) SetValue(v string) {
	o.Value = &v
}

func (o V202101beta1MeshMetric) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1MeshMetric struct {
	value *V202101beta1MeshMetric
	isSet bool
}

func (v NullableV202101beta1MeshMetric) Get() *V202101beta1MeshMetric {
	return v.value
}

func (v *NullableV202101beta1MeshMetric) Set(val *V202101beta1MeshMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1MeshMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1MeshMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1MeshMetric(val *V202101beta1MeshMetric) *NullableV202101beta1MeshMetric {
	return &NullableV202101beta1MeshMetric{value: val, isSet: true}
}

func (v NullableV202101beta1MeshMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1MeshMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
