/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1AgentHealth struct for V202101beta1AgentHealth
type V202101beta1AgentHealth struct {
	Agent         *V202101beta1Agent          `json:"agent,omitempty"`
	Health        *[]V202101beta1HealthMoment `json:"health,omitempty"`
	OverallHealth *V202101beta1Health         `json:"overallHealth,omitempty"`
}

// NewV202101beta1AgentHealth instantiates a new V202101beta1AgentHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1AgentHealth() *V202101beta1AgentHealth {
	this := V202101beta1AgentHealth{}
	return &this
}

// NewV202101beta1AgentHealthWithDefaults instantiates a new V202101beta1AgentHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1AgentHealthWithDefaults() *V202101beta1AgentHealth {
	this := V202101beta1AgentHealth{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *V202101beta1AgentHealth) GetAgent() V202101beta1Agent {
	if o == nil || o.Agent == nil {
		var ret V202101beta1Agent
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1AgentHealth) GetAgentOk() (*V202101beta1Agent, bool) {
	if o == nil || o.Agent == nil {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *V202101beta1AgentHealth) HasAgent() bool {
	if o != nil && o.Agent != nil {
		return true
	}

	return false
}

// SetAgent gets a reference to the given V202101beta1Agent and assigns it to the Agent field.
func (o *V202101beta1AgentHealth) SetAgent(v V202101beta1Agent) {
	o.Agent = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *V202101beta1AgentHealth) GetHealth() []V202101beta1HealthMoment {
	if o == nil || o.Health == nil {
		var ret []V202101beta1HealthMoment
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1AgentHealth) GetHealthOk() (*[]V202101beta1HealthMoment, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *V202101beta1AgentHealth) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given []V202101beta1HealthMoment and assigns it to the Health field.
func (o *V202101beta1AgentHealth) SetHealth(v []V202101beta1HealthMoment) {
	o.Health = &v
}

// GetOverallHealth returns the OverallHealth field value if set, zero value otherwise.
func (o *V202101beta1AgentHealth) GetOverallHealth() V202101beta1Health {
	if o == nil || o.OverallHealth == nil {
		var ret V202101beta1Health
		return ret
	}
	return *o.OverallHealth
}

// GetOverallHealthOk returns a tuple with the OverallHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1AgentHealth) GetOverallHealthOk() (*V202101beta1Health, bool) {
	if o == nil || o.OverallHealth == nil {
		return nil, false
	}
	return o.OverallHealth, true
}

// HasOverallHealth returns a boolean if a field has been set.
func (o *V202101beta1AgentHealth) HasOverallHealth() bool {
	if o != nil && o.OverallHealth != nil {
		return true
	}

	return false
}

// SetOverallHealth gets a reference to the given V202101beta1Health and assigns it to the OverallHealth field.
func (o *V202101beta1AgentHealth) SetOverallHealth(v V202101beta1Health) {
	o.OverallHealth = &v
}

func (o V202101beta1AgentHealth) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agent != nil {
		toSerialize["agent"] = o.Agent
	}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	if o.OverallHealth != nil {
		toSerialize["overallHealth"] = o.OverallHealth
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1AgentHealth struct {
	value *V202101beta1AgentHealth
	isSet bool
}

func (v NullableV202101beta1AgentHealth) Get() *V202101beta1AgentHealth {
	return v.value
}

func (v *NullableV202101beta1AgentHealth) Set(val *V202101beta1AgentHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1AgentHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1AgentHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1AgentHealth(val *V202101beta1AgentHealth) *NullableV202101beta1AgentHealth {
	return &NullableV202101beta1AgentHealth{value: val, isSet: true}
}

func (v NullableV202101beta1AgentHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1AgentHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
