/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1TestMonitoringSettings struct for V202101beta1TestMonitoringSettings
type V202101beta1TestMonitoringSettings struct {
	ActivationGracePeriod *string   `json:"activationGracePeriod,omitempty"`
	ActivationTimeUnit    *string   `json:"activationTimeUnit,omitempty"`
	ActivationTimeWindow  *string   `json:"activationTimeWindow,omitempty"`
	ActivationTimes       *string   `json:"activationTimes,omitempty"`
	NotificationChannels  *[]string `json:"notificationChannels,omitempty"`
}

// NewV202101beta1TestMonitoringSettings instantiates a new V202101beta1TestMonitoringSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1TestMonitoringSettings() *V202101beta1TestMonitoringSettings {
	this := V202101beta1TestMonitoringSettings{}
	return &this
}

// NewV202101beta1TestMonitoringSettingsWithDefaults instantiates a new V202101beta1TestMonitoringSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1TestMonitoringSettingsWithDefaults() *V202101beta1TestMonitoringSettings {
	this := V202101beta1TestMonitoringSettings{}
	return &this
}

// GetActivationGracePeriod returns the ActivationGracePeriod field value if set, zero value otherwise.
func (o *V202101beta1TestMonitoringSettings) GetActivationGracePeriod() string {
	if o == nil || o.ActivationGracePeriod == nil {
		var ret string
		return ret
	}
	return *o.ActivationGracePeriod
}

// GetActivationGracePeriodOk returns a tuple with the ActivationGracePeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TestMonitoringSettings) GetActivationGracePeriodOk() (*string, bool) {
	if o == nil || o.ActivationGracePeriod == nil {
		return nil, false
	}
	return o.ActivationGracePeriod, true
}

// HasActivationGracePeriod returns a boolean if a field has been set.
func (o *V202101beta1TestMonitoringSettings) HasActivationGracePeriod() bool {
	if o != nil && o.ActivationGracePeriod != nil {
		return true
	}

	return false
}

// SetActivationGracePeriod gets a reference to the given string and assigns it to the ActivationGracePeriod field.
func (o *V202101beta1TestMonitoringSettings) SetActivationGracePeriod(v string) {
	o.ActivationGracePeriod = &v
}

// GetActivationTimeUnit returns the ActivationTimeUnit field value if set, zero value otherwise.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimeUnit() string {
	if o == nil || o.ActivationTimeUnit == nil {
		var ret string
		return ret
	}
	return *o.ActivationTimeUnit
}

// GetActivationTimeUnitOk returns a tuple with the ActivationTimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimeUnitOk() (*string, bool) {
	if o == nil || o.ActivationTimeUnit == nil {
		return nil, false
	}
	return o.ActivationTimeUnit, true
}

// HasActivationTimeUnit returns a boolean if a field has been set.
func (o *V202101beta1TestMonitoringSettings) HasActivationTimeUnit() bool {
	if o != nil && o.ActivationTimeUnit != nil {
		return true
	}

	return false
}

// SetActivationTimeUnit gets a reference to the given string and assigns it to the ActivationTimeUnit field.
func (o *V202101beta1TestMonitoringSettings) SetActivationTimeUnit(v string) {
	o.ActivationTimeUnit = &v
}

// GetActivationTimeWindow returns the ActivationTimeWindow field value if set, zero value otherwise.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimeWindow() string {
	if o == nil || o.ActivationTimeWindow == nil {
		var ret string
		return ret
	}
	return *o.ActivationTimeWindow
}

// GetActivationTimeWindowOk returns a tuple with the ActivationTimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimeWindowOk() (*string, bool) {
	if o == nil || o.ActivationTimeWindow == nil {
		return nil, false
	}
	return o.ActivationTimeWindow, true
}

// HasActivationTimeWindow returns a boolean if a field has been set.
func (o *V202101beta1TestMonitoringSettings) HasActivationTimeWindow() bool {
	if o != nil && o.ActivationTimeWindow != nil {
		return true
	}

	return false
}

// SetActivationTimeWindow gets a reference to the given string and assigns it to the ActivationTimeWindow field.
func (o *V202101beta1TestMonitoringSettings) SetActivationTimeWindow(v string) {
	o.ActivationTimeWindow = &v
}

// GetActivationTimes returns the ActivationTimes field value if set, zero value otherwise.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimes() string {
	if o == nil || o.ActivationTimes == nil {
		var ret string
		return ret
	}
	return *o.ActivationTimes
}

// GetActivationTimesOk returns a tuple with the ActivationTimes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TestMonitoringSettings) GetActivationTimesOk() (*string, bool) {
	if o == nil || o.ActivationTimes == nil {
		return nil, false
	}
	return o.ActivationTimes, true
}

// HasActivationTimes returns a boolean if a field has been set.
func (o *V202101beta1TestMonitoringSettings) HasActivationTimes() bool {
	if o != nil && o.ActivationTimes != nil {
		return true
	}

	return false
}

// SetActivationTimes gets a reference to the given string and assigns it to the ActivationTimes field.
func (o *V202101beta1TestMonitoringSettings) SetActivationTimes(v string) {
	o.ActivationTimes = &v
}

// GetNotificationChannels returns the NotificationChannels field value if set, zero value otherwise.
func (o *V202101beta1TestMonitoringSettings) GetNotificationChannels() []string {
	if o == nil || o.NotificationChannels == nil {
		var ret []string
		return ret
	}
	return *o.NotificationChannels
}

// GetNotificationChannelsOk returns a tuple with the NotificationChannels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TestMonitoringSettings) GetNotificationChannelsOk() (*[]string, bool) {
	if o == nil || o.NotificationChannels == nil {
		return nil, false
	}
	return o.NotificationChannels, true
}

// HasNotificationChannels returns a boolean if a field has been set.
func (o *V202101beta1TestMonitoringSettings) HasNotificationChannels() bool {
	if o != nil && o.NotificationChannels != nil {
		return true
	}

	return false
}

// SetNotificationChannels gets a reference to the given []string and assigns it to the NotificationChannels field.
func (o *V202101beta1TestMonitoringSettings) SetNotificationChannels(v []string) {
	o.NotificationChannels = &v
}

func (o V202101beta1TestMonitoringSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActivationGracePeriod != nil {
		toSerialize["activationGracePeriod"] = o.ActivationGracePeriod
	}
	if o.ActivationTimeUnit != nil {
		toSerialize["activationTimeUnit"] = o.ActivationTimeUnit
	}
	if o.ActivationTimeWindow != nil {
		toSerialize["activationTimeWindow"] = o.ActivationTimeWindow
	}
	if o.ActivationTimes != nil {
		toSerialize["activationTimes"] = o.ActivationTimes
	}
	if o.NotificationChannels != nil {
		toSerialize["notificationChannels"] = o.NotificationChannels
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1TestMonitoringSettings struct {
	value *V202101beta1TestMonitoringSettings
	isSet bool
}

func (v NullableV202101beta1TestMonitoringSettings) Get() *V202101beta1TestMonitoringSettings {
	return v.value
}

func (v *NullableV202101beta1TestMonitoringSettings) Set(val *V202101beta1TestMonitoringSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1TestMonitoringSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1TestMonitoringSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1TestMonitoringSettings(val *V202101beta1TestMonitoringSettings) *NullableV202101beta1TestMonitoringSettings {
	return &NullableV202101beta1TestMonitoringSettings{value: val, isSet: true}
}

func (v NullableV202101beta1TestMonitoringSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1TestMonitoringSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
