/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1AgentTaskConfig struct for V202101beta1AgentTaskConfig
type V202101beta1AgentTaskConfig struct {
	Id      *string   `json:"id,omitempty"`
	Targets *[]string `json:"targets,omitempty"`
}

// NewV202101beta1AgentTaskConfig instantiates a new V202101beta1AgentTaskConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1AgentTaskConfig() *V202101beta1AgentTaskConfig {
	this := V202101beta1AgentTaskConfig{}
	return &this
}

// NewV202101beta1AgentTaskConfigWithDefaults instantiates a new V202101beta1AgentTaskConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1AgentTaskConfigWithDefaults() *V202101beta1AgentTaskConfig {
	this := V202101beta1AgentTaskConfig{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1AgentTaskConfig) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1AgentTaskConfig) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1AgentTaskConfig) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1AgentTaskConfig) SetId(v string) {
	o.Id = &v
}

// GetTargets returns the Targets field value if set, zero value otherwise.
func (o *V202101beta1AgentTaskConfig) GetTargets() []string {
	if o == nil || o.Targets == nil {
		var ret []string
		return ret
	}
	return *o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1AgentTaskConfig) GetTargetsOk() (*[]string, bool) {
	if o == nil || o.Targets == nil {
		return nil, false
	}
	return o.Targets, true
}

// HasTargets returns a boolean if a field has been set.
func (o *V202101beta1AgentTaskConfig) HasTargets() bool {
	if o != nil && o.Targets != nil {
		return true
	}

	return false
}

// SetTargets gets a reference to the given []string and assigns it to the Targets field.
func (o *V202101beta1AgentTaskConfig) SetTargets(v []string) {
	o.Targets = &v
}

func (o V202101beta1AgentTaskConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Targets != nil {
		toSerialize["targets"] = o.Targets
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1AgentTaskConfig struct {
	value *V202101beta1AgentTaskConfig
	isSet bool
}

func (v NullableV202101beta1AgentTaskConfig) Get() *V202101beta1AgentTaskConfig {
	return v.value
}

func (v *NullableV202101beta1AgentTaskConfig) Set(val *V202101beta1AgentTaskConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1AgentTaskConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1AgentTaskConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1AgentTaskConfig(val *V202101beta1AgentTaskConfig) *NullableV202101beta1AgentTaskConfig {
	return &NullableV202101beta1AgentTaskConfig{value: val, isSet: true}
}

func (v NullableV202101beta1AgentTaskConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1AgentTaskConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
