/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
	"time"
)

// V202101beta1Agent struct for V202101beta1Agent
type V202101beta1Agent struct {
	Id         *string                  `json:"id,omitempty"`
	Name       *string                  `json:"name,omitempty"`
	Status     *V202101beta1AgentStatus `json:"status,omitempty"`
	Alias      *string                  `json:"alias,omitempty"`
	Type       *string                  `json:"type,omitempty"`
	Os         *string                  `json:"os,omitempty"`
	Ip         *string                  `json:"ip,omitempty"`
	Lat        *float64                 `json:"lat,omitempty"`
	Long       *float64                 `json:"long,omitempty"`
	LastAuthed *time.Time               `json:"lastAuthed,omitempty"`
	Family     *V202101beta1IPFamily    `json:"family,omitempty"`
	Asn        *int64                   `json:"asn,omitempty"`
	SiteId     *string                  `json:"siteId,omitempty"`
	Version    *string                  `json:"version,omitempty"`
	Challenge  *string                  `json:"challenge,omitempty"`
	City       *string                  `json:"city,omitempty"`
	Region     *string                  `json:"region,omitempty"`
	Country    *string                  `json:"country,omitempty"`
	TestIds    *[]string                `json:"testIds,omitempty"`
	LocalIp    *string                  `json:"localIp,omitempty"`
}

// NewV202101beta1Agent instantiates a new V202101beta1Agent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1Agent() *V202101beta1Agent {
	this := V202101beta1Agent{}
	var status V202101beta1AgentStatus = V202101BETA1AGENTSTATUS_UNSPECIFIED
	this.Status = &status
	var family V202101beta1IPFamily = V202101BETA1IPFAMILY_UNSPECIFIED
	this.Family = &family
	return &this
}

// NewV202101beta1AgentWithDefaults instantiates a new V202101beta1Agent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1AgentWithDefaults() *V202101beta1Agent {
	this := V202101beta1Agent{}
	var status V202101beta1AgentStatus = V202101BETA1AGENTSTATUS_UNSPECIFIED
	this.Status = &status
	var family V202101beta1IPFamily = V202101BETA1IPFAMILY_UNSPECIFIED
	this.Family = &family
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1Agent) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V202101beta1Agent) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetStatus() V202101beta1AgentStatus {
	if o == nil || o.Status == nil {
		var ret V202101beta1AgentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetStatusOk() (*V202101beta1AgentStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given V202101beta1AgentStatus and assigns it to the Status field.
func (o *V202101beta1Agent) SetStatus(v V202101beta1AgentStatus) {
	o.Status = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetAlias() string {
	if o == nil || o.Alias == nil {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetAliasOk() (*string, bool) {
	if o == nil || o.Alias == nil {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasAlias() bool {
	if o != nil && o.Alias != nil {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *V202101beta1Agent) SetAlias(v string) {
	o.Alias = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V202101beta1Agent) SetType(v string) {
	o.Type = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetOs() string {
	if o == nil || o.Os == nil {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetOsOk() (*string, bool) {
	if o == nil || o.Os == nil {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasOs() bool {
	if o != nil && o.Os != nil {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *V202101beta1Agent) SetOs(v string) {
	o.Os = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *V202101beta1Agent) SetIp(v string) {
	o.Ip = &v
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetLat() float64 {
	if o == nil || o.Lat == nil {
		var ret float64
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetLatOk() (*float64, bool) {
	if o == nil || o.Lat == nil {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasLat() bool {
	if o != nil && o.Lat != nil {
		return true
	}

	return false
}

// SetLat gets a reference to the given float64 and assigns it to the Lat field.
func (o *V202101beta1Agent) SetLat(v float64) {
	o.Lat = &v
}

// GetLong returns the Long field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetLong() float64 {
	if o == nil || o.Long == nil {
		var ret float64
		return ret
	}
	return *o.Long
}

// GetLongOk returns a tuple with the Long field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetLongOk() (*float64, bool) {
	if o == nil || o.Long == nil {
		return nil, false
	}
	return o.Long, true
}

// HasLong returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasLong() bool {
	if o != nil && o.Long != nil {
		return true
	}

	return false
}

// SetLong gets a reference to the given float64 and assigns it to the Long field.
func (o *V202101beta1Agent) SetLong(v float64) {
	o.Long = &v
}

// GetLastAuthed returns the LastAuthed field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetLastAuthed() time.Time {
	if o == nil || o.LastAuthed == nil {
		var ret time.Time
		return ret
	}
	return *o.LastAuthed
}

// GetLastAuthedOk returns a tuple with the LastAuthed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetLastAuthedOk() (*time.Time, bool) {
	if o == nil || o.LastAuthed == nil {
		return nil, false
	}
	return o.LastAuthed, true
}

// HasLastAuthed returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasLastAuthed() bool {
	if o != nil && o.LastAuthed != nil {
		return true
	}

	return false
}

// SetLastAuthed gets a reference to the given time.Time and assigns it to the LastAuthed field.
func (o *V202101beta1Agent) SetLastAuthed(v time.Time) {
	o.LastAuthed = &v
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetFamily() V202101beta1IPFamily {
	if o == nil || o.Family == nil {
		var ret V202101beta1IPFamily
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetFamilyOk() (*V202101beta1IPFamily, bool) {
	if o == nil || o.Family == nil {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasFamily() bool {
	if o != nil && o.Family != nil {
		return true
	}

	return false
}

// SetFamily gets a reference to the given V202101beta1IPFamily and assigns it to the Family field.
func (o *V202101beta1Agent) SetFamily(v V202101beta1IPFamily) {
	o.Family = &v
}

// GetAsn returns the Asn field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetAsn() int64 {
	if o == nil || o.Asn == nil {
		var ret int64
		return ret
	}
	return *o.Asn
}

// GetAsnOk returns a tuple with the Asn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetAsnOk() (*int64, bool) {
	if o == nil || o.Asn == nil {
		return nil, false
	}
	return o.Asn, true
}

// HasAsn returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasAsn() bool {
	if o != nil && o.Asn != nil {
		return true
	}

	return false
}

// SetAsn gets a reference to the given int64 and assigns it to the Asn field.
func (o *V202101beta1Agent) SetAsn(v int64) {
	o.Asn = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetSiteId() string {
	if o == nil || o.SiteId == nil {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetSiteIdOk() (*string, bool) {
	if o == nil || o.SiteId == nil {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasSiteId() bool {
	if o != nil && o.SiteId != nil {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *V202101beta1Agent) SetSiteId(v string) {
	o.SiteId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *V202101beta1Agent) SetVersion(v string) {
	o.Version = &v
}

// GetChallenge returns the Challenge field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetChallenge() string {
	if o == nil || o.Challenge == nil {
		var ret string
		return ret
	}
	return *o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetChallengeOk() (*string, bool) {
	if o == nil || o.Challenge == nil {
		return nil, false
	}
	return o.Challenge, true
}

// HasChallenge returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasChallenge() bool {
	if o != nil && o.Challenge != nil {
		return true
	}

	return false
}

// SetChallenge gets a reference to the given string and assigns it to the Challenge field.
func (o *V202101beta1Agent) SetChallenge(v string) {
	o.Challenge = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *V202101beta1Agent) SetCity(v string) {
	o.City = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetRegionOk() (*string, bool) {
	if o == nil || o.Region == nil {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasRegion() bool {
	if o != nil && o.Region != nil {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *V202101beta1Agent) SetRegion(v string) {
	o.Region = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *V202101beta1Agent) SetCountry(v string) {
	o.Country = &v
}

// GetTestIds returns the TestIds field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetTestIds() []string {
	if o == nil || o.TestIds == nil {
		var ret []string
		return ret
	}
	return *o.TestIds
}

// GetTestIdsOk returns a tuple with the TestIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetTestIdsOk() (*[]string, bool) {
	if o == nil || o.TestIds == nil {
		return nil, false
	}
	return o.TestIds, true
}

// HasTestIds returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasTestIds() bool {
	if o != nil && o.TestIds != nil {
		return true
	}

	return false
}

// SetTestIds gets a reference to the given []string and assigns it to the TestIds field.
func (o *V202101beta1Agent) SetTestIds(v []string) {
	o.TestIds = &v
}

// GetLocalIp returns the LocalIp field value if set, zero value otherwise.
func (o *V202101beta1Agent) GetLocalIp() string {
	if o == nil || o.LocalIp == nil {
		var ret string
		return ret
	}
	return *o.LocalIp
}

// GetLocalIpOk returns a tuple with the LocalIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1Agent) GetLocalIpOk() (*string, bool) {
	if o == nil || o.LocalIp == nil {
		return nil, false
	}
	return o.LocalIp, true
}

// HasLocalIp returns a boolean if a field has been set.
func (o *V202101beta1Agent) HasLocalIp() bool {
	if o != nil && o.LocalIp != nil {
		return true
	}

	return false
}

// SetLocalIp gets a reference to the given string and assigns it to the LocalIp field.
func (o *V202101beta1Agent) SetLocalIp(v string) {
	o.LocalIp = &v
}

func (o V202101beta1Agent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Alias != nil {
		toSerialize["alias"] = o.Alias
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Os != nil {
		toSerialize["os"] = o.Os
	}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	if o.Lat != nil {
		toSerialize["lat"] = o.Lat
	}
	if o.Long != nil {
		toSerialize["long"] = o.Long
	}
	if o.LastAuthed != nil {
		toSerialize["lastAuthed"] = o.LastAuthed
	}
	if o.Family != nil {
		toSerialize["family"] = o.Family
	}
	if o.Asn != nil {
		toSerialize["asn"] = o.Asn
	}
	if o.SiteId != nil {
		toSerialize["siteId"] = o.SiteId
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Challenge != nil {
		toSerialize["challenge"] = o.Challenge
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.Region != nil {
		toSerialize["region"] = o.Region
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.TestIds != nil {
		toSerialize["testIds"] = o.TestIds
	}
	if o.LocalIp != nil {
		toSerialize["localIp"] = o.LocalIp
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1Agent struct {
	value *V202101beta1Agent
	isSet bool
}

func (v NullableV202101beta1Agent) Get() *V202101beta1Agent {
	return v.value
}

func (v *NullableV202101beta1Agent) Set(val *V202101beta1Agent) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1Agent) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1Agent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1Agent(val *V202101beta1Agent) *NullableV202101beta1Agent {
	return &NullableV202101beta1Agent{value: val, isSet: true}
}

func (v NullableV202101beta1Agent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1Agent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
