/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
	"time"
)

// V202101beta1GetHealthForTestsRequest struct for V202101beta1GetHealthForTestsRequest
type V202101beta1GetHealthForTestsRequest struct {
	// List of ids of the tests to get health for.
	Ids *[]string `json:"ids,omitempty"`
	// Start of the time interval for this query.
	StartTime *time.Time `json:"startTime,omitempty"`
	// End of the time interval for this query.
	EndTime  *time.Time `json:"endTime,omitempty"`
	AgentIds *[]string  `json:"agentIds,omitempty"`
	// Optionally only look at a subset of tasks -- this lets you limit targets.
	TaskIds *[]string `json:"taskIds,omitempty"`
}

// NewV202101beta1GetHealthForTestsRequest instantiates a new V202101beta1GetHealthForTestsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1GetHealthForTestsRequest() *V202101beta1GetHealthForTestsRequest {
	this := V202101beta1GetHealthForTestsRequest{}
	return &this
}

// NewV202101beta1GetHealthForTestsRequestWithDefaults instantiates a new V202101beta1GetHealthForTestsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1GetHealthForTestsRequestWithDefaults() *V202101beta1GetHealthForTestsRequest {
	this := V202101beta1GetHealthForTestsRequest{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *V202101beta1GetHealthForTestsRequest) GetIds() []string {
	if o == nil || o.Ids == nil {
		var ret []string
		return ret
	}
	return *o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetHealthForTestsRequest) GetIdsOk() (*[]string, bool) {
	if o == nil || o.Ids == nil {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *V202101beta1GetHealthForTestsRequest) HasIds() bool {
	if o != nil && o.Ids != nil {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *V202101beta1GetHealthForTestsRequest) SetIds(v []string) {
	o.Ids = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *V202101beta1GetHealthForTestsRequest) GetStartTime() time.Time {
	if o == nil || o.StartTime == nil {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetHealthForTestsRequest) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *V202101beta1GetHealthForTestsRequest) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *V202101beta1GetHealthForTestsRequest) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *V202101beta1GetHealthForTestsRequest) GetEndTime() time.Time {
	if o == nil || o.EndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetHealthForTestsRequest) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || o.EndTime == nil {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *V202101beta1GetHealthForTestsRequest) HasEndTime() bool {
	if o != nil && o.EndTime != nil {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *V202101beta1GetHealthForTestsRequest) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetAgentIds returns the AgentIds field value if set, zero value otherwise.
func (o *V202101beta1GetHealthForTestsRequest) GetAgentIds() []string {
	if o == nil || o.AgentIds == nil {
		var ret []string
		return ret
	}
	return *o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetHealthForTestsRequest) GetAgentIdsOk() (*[]string, bool) {
	if o == nil || o.AgentIds == nil {
		return nil, false
	}
	return o.AgentIds, true
}

// HasAgentIds returns a boolean if a field has been set.
func (o *V202101beta1GetHealthForTestsRequest) HasAgentIds() bool {
	if o != nil && o.AgentIds != nil {
		return true
	}

	return false
}

// SetAgentIds gets a reference to the given []string and assigns it to the AgentIds field.
func (o *V202101beta1GetHealthForTestsRequest) SetAgentIds(v []string) {
	o.AgentIds = &v
}

// GetTaskIds returns the TaskIds field value if set, zero value otherwise.
func (o *V202101beta1GetHealthForTestsRequest) GetTaskIds() []string {
	if o == nil || o.TaskIds == nil {
		var ret []string
		return ret
	}
	return *o.TaskIds
}

// GetTaskIdsOk returns a tuple with the TaskIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetHealthForTestsRequest) GetTaskIdsOk() (*[]string, bool) {
	if o == nil || o.TaskIds == nil {
		return nil, false
	}
	return o.TaskIds, true
}

// HasTaskIds returns a boolean if a field has been set.
func (o *V202101beta1GetHealthForTestsRequest) HasTaskIds() bool {
	if o != nil && o.TaskIds != nil {
		return true
	}

	return false
}

// SetTaskIds gets a reference to the given []string and assigns it to the TaskIds field.
func (o *V202101beta1GetHealthForTestsRequest) SetTaskIds(v []string) {
	o.TaskIds = &v
}

func (o V202101beta1GetHealthForTestsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ids != nil {
		toSerialize["ids"] = o.Ids
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.EndTime != nil {
		toSerialize["endTime"] = o.EndTime
	}
	if o.AgentIds != nil {
		toSerialize["agentIds"] = o.AgentIds
	}
	if o.TaskIds != nil {
		toSerialize["taskIds"] = o.TaskIds
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1GetHealthForTestsRequest struct {
	value *V202101beta1GetHealthForTestsRequest
	isSet bool
}

func (v NullableV202101beta1GetHealthForTestsRequest) Get() *V202101beta1GetHealthForTestsRequest {
	return v.value
}

func (v *NullableV202101beta1GetHealthForTestsRequest) Set(val *V202101beta1GetHealthForTestsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1GetHealthForTestsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1GetHealthForTestsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1GetHealthForTestsRequest(val *V202101beta1GetHealthForTestsRequest) *NullableV202101beta1GetHealthForTestsRequest {
	return &NullableV202101beta1GetHealthForTestsRequest{value: val, isSet: true}
}

func (v NullableV202101beta1GetHealthForTestsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1GetHealthForTestsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
