/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1MeshColumn struct for V202101beta1MeshColumn
type V202101beta1MeshColumn struct {
	Id      *string                    `json:"id,omitempty"`
	Name    *string                    `json:"name,omitempty"`
	Alias   *string                    `json:"alias,omitempty"`
	Target  *string                    `json:"target,omitempty"`
	Metrics *V202101beta1MeshMetrics   `json:"metrics,omitempty"`
	Health  *[]V202101beta1MeshMetrics `json:"health,omitempty"`
}

// NewV202101beta1MeshColumn instantiates a new V202101beta1MeshColumn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1MeshColumn() *V202101beta1MeshColumn {
	this := V202101beta1MeshColumn{}
	return &this
}

// NewV202101beta1MeshColumnWithDefaults instantiates a new V202101beta1MeshColumn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1MeshColumnWithDefaults() *V202101beta1MeshColumn {
	this := V202101beta1MeshColumn{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1MeshColumn) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V202101beta1MeshColumn) SetName(v string) {
	o.Name = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetAlias() string {
	if o == nil || o.Alias == nil {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetAliasOk() (*string, bool) {
	if o == nil || o.Alias == nil {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasAlias() bool {
	if o != nil && o.Alias != nil {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *V202101beta1MeshColumn) SetAlias(v string) {
	o.Alias = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetTarget() string {
	if o == nil || o.Target == nil {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetTargetOk() (*string, bool) {
	if o == nil || o.Target == nil {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasTarget() bool {
	if o != nil && o.Target != nil {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *V202101beta1MeshColumn) SetTarget(v string) {
	o.Target = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetMetrics() V202101beta1MeshMetrics {
	if o == nil || o.Metrics == nil {
		var ret V202101beta1MeshMetrics
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetMetricsOk() (*V202101beta1MeshMetrics, bool) {
	if o == nil || o.Metrics == nil {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasMetrics() bool {
	if o != nil && o.Metrics != nil {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given V202101beta1MeshMetrics and assigns it to the Metrics field.
func (o *V202101beta1MeshColumn) SetMetrics(v V202101beta1MeshMetrics) {
	o.Metrics = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *V202101beta1MeshColumn) GetHealth() []V202101beta1MeshMetrics {
	if o == nil || o.Health == nil {
		var ret []V202101beta1MeshMetrics
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1MeshColumn) GetHealthOk() (*[]V202101beta1MeshMetrics, bool) {
	if o == nil || o.Health == nil {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *V202101beta1MeshColumn) HasHealth() bool {
	if o != nil && o.Health != nil {
		return true
	}

	return false
}

// SetHealth gets a reference to the given []V202101beta1MeshMetrics and assigns it to the Health field.
func (o *V202101beta1MeshColumn) SetHealth(v []V202101beta1MeshMetrics) {
	o.Health = &v
}

func (o V202101beta1MeshColumn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Alias != nil {
		toSerialize["alias"] = o.Alias
	}
	if o.Target != nil {
		toSerialize["target"] = o.Target
	}
	if o.Metrics != nil {
		toSerialize["metrics"] = o.Metrics
	}
	if o.Health != nil {
		toSerialize["health"] = o.Health
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1MeshColumn struct {
	value *V202101beta1MeshColumn
	isSet bool
}

func (v NullableV202101beta1MeshColumn) Get() *V202101beta1MeshColumn {
	return v.value
}

func (v *NullableV202101beta1MeshColumn) Set(val *V202101beta1MeshColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1MeshColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1MeshColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1MeshColumn(val *V202101beta1MeshColumn) *NullableV202101beta1MeshColumn {
	return &NullableV202101beta1MeshColumn{value: val, isSet: true}
}

func (v NullableV202101beta1MeshColumn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1MeshColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
