/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1TraceHop struct for V202101beta1TraceHop
type V202101beta1TraceHop struct {
	Agent     *bool     `json:"agent,omitempty"`
	AgentId   *string   `json:"agentId,omitempty"`
	Ttl       *int32    `json:"ttl,omitempty"`
	Ip        *string   `json:"ip,omitempty"`
	Latencies *[]string `json:"latencies,omitempty"`
	Timeout   *bool     `json:"timeout,omitempty"`
}

// NewV202101beta1TraceHop instantiates a new V202101beta1TraceHop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1TraceHop() *V202101beta1TraceHop {
	this := V202101beta1TraceHop{}
	return &this
}

// NewV202101beta1TraceHopWithDefaults instantiates a new V202101beta1TraceHop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1TraceHopWithDefaults() *V202101beta1TraceHop {
	this := V202101beta1TraceHop{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetAgent() bool {
	if o == nil || o.Agent == nil {
		var ret bool
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetAgentOk() (*bool, bool) {
	if o == nil || o.Agent == nil {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasAgent() bool {
	if o != nil && o.Agent != nil {
		return true
	}

	return false
}

// SetAgent gets a reference to the given bool and assigns it to the Agent field.
func (o *V202101beta1TraceHop) SetAgent(v bool) {
	o.Agent = &v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetAgentId() string {
	if o == nil || o.AgentId == nil {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetAgentIdOk() (*string, bool) {
	if o == nil || o.AgentId == nil {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasAgentId() bool {
	if o != nil && o.AgentId != nil {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *V202101beta1TraceHop) SetAgentId(v string) {
	o.AgentId = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetTtl() int32 {
	if o == nil || o.Ttl == nil {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetTtlOk() (*int32, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *V202101beta1TraceHop) SetTtl(v int32) {
	o.Ttl = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *V202101beta1TraceHop) SetIp(v string) {
	o.Ip = &v
}

// GetLatencies returns the Latencies field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetLatencies() []string {
	if o == nil || o.Latencies == nil {
		var ret []string
		return ret
	}
	return *o.Latencies
}

// GetLatenciesOk returns a tuple with the Latencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetLatenciesOk() (*[]string, bool) {
	if o == nil || o.Latencies == nil {
		return nil, false
	}
	return o.Latencies, true
}

// HasLatencies returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasLatencies() bool {
	if o != nil && o.Latencies != nil {
		return true
	}

	return false
}

// SetLatencies gets a reference to the given []string and assigns it to the Latencies field.
func (o *V202101beta1TraceHop) SetLatencies(v []string) {
	o.Latencies = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *V202101beta1TraceHop) GetTimeout() bool {
	if o == nil || o.Timeout == nil {
		var ret bool
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1TraceHop) GetTimeoutOk() (*bool, bool) {
	if o == nil || o.Timeout == nil {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *V202101beta1TraceHop) HasTimeout() bool {
	if o != nil && o.Timeout != nil {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given bool and assigns it to the Timeout field.
func (o *V202101beta1TraceHop) SetTimeout(v bool) {
	o.Timeout = &v
}

func (o V202101beta1TraceHop) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agent != nil {
		toSerialize["agent"] = o.Agent
	}
	if o.AgentId != nil {
		toSerialize["agentId"] = o.AgentId
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	if o.Latencies != nil {
		toSerialize["latencies"] = o.Latencies
	}
	if o.Timeout != nil {
		toSerialize["timeout"] = o.Timeout
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1TraceHop struct {
	value *V202101beta1TraceHop
	isSet bool
}

func (v NullableV202101beta1TraceHop) Get() *V202101beta1TraceHop {
	return v.value
}

func (v *NullableV202101beta1TraceHop) Set(val *V202101beta1TraceHop) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1TraceHop) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1TraceHop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1TraceHop(val *V202101beta1TraceHop) *NullableV202101beta1TraceHop {
	return &NullableV202101beta1TraceHop{value: val, isSet: true}
}

func (v NullableV202101beta1TraceHop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1TraceHop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
