/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudexportstub

import (
	"context"
	"net/http"
)

// CloudExportAdminServiceApiRouter defines the required methods for binding the api requests to a responses for the CloudExportAdminServiceAPI
// The CloudExportAdminServiceApiRouter implementation should parse necessary information from the http request,
// pass the data to a CloudExportAdminServiceApiServicer to perform the required actions, then write the service results to the http response.
type CloudExportAdminServiceApiRouter interface {
	ExportCreate(http.ResponseWriter, *http.Request)
	ExportDelete(http.ResponseWriter, *http.Request)
	ExportGet(http.ResponseWriter, *http.Request)
	ExportList(http.ResponseWriter, *http.Request)
	ExportPatch(http.ResponseWriter, *http.Request)
	ExportUpdate(http.ResponseWriter, *http.Request)
}

// CloudExportAdminServiceApiServicer defines the api actions for the CloudExportAdminServiceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CloudExportAdminServiceApiServicer interface {
	ExportCreate(context.Context, V202101beta1CreateCloudExportRequest) (ImplResponse, error)
	ExportDelete(context.Context, string) (ImplResponse, error)
	ExportGet(context.Context, string) (ImplResponse, error)
	ExportList(context.Context) (ImplResponse, error)
	ExportPatch(context.Context, string, V202101beta1PatchCloudExportRequest) (ImplResponse, error)
	ExportUpdate(context.Context, string, V202101beta1UpdateCloudExportRequest) (ImplResponse, error)
}
