/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudexportstub

import (
	"context"
	"net/http"
)

// CloudExportAdminServiceApiRouter defines the required methods for binding the api requests to a responses for the CloudExportAdminServiceApi
// The CloudExportAdminServiceApiRouter implementation should parse necessary information from the http request,
// pass the data to a CloudExportAdminServiceApiServicer to perform the required actions, then write the service results to the http response.
type CloudExportAdminServiceApiRouter interface {
	CloudExportAdminServiceCreateCloudExport(http.ResponseWriter, *http.Request)
	CloudExportAdminServiceDeleteCloudExport(http.ResponseWriter, *http.Request)
	CloudExportAdminServiceGetCloudExport(http.ResponseWriter, *http.Request)
	CloudExportAdminServiceListCloudExport(http.ResponseWriter, *http.Request)
	CloudExportAdminServicePatchCloudExport(http.ResponseWriter, *http.Request)
	CloudExportAdminServiceUpdateCloudExport(http.ResponseWriter, *http.Request)
}

// CloudExportAdminServiceApiServicer defines the api actions for the CloudExportAdminServiceApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CloudExportAdminServiceApiServicer interface {
	CloudExportAdminServiceCreateCloudExport(context.Context, V202101beta1CreateCloudExportRequest) (ImplResponse, error)
	CloudExportAdminServiceDeleteCloudExport(context.Context, string) (ImplResponse, error)
	CloudExportAdminServiceGetCloudExport(context.Context, string) (ImplResponse, error)
	CloudExportAdminServiceListCloudExport(context.Context) (ImplResponse, error)
	CloudExportAdminServicePatchCloudExport(context.Context, string, V202101beta1PatchCloudExportRequest) (ImplResponse, error)
	CloudExportAdminServiceUpdateCloudExport(context.Context, string, V202101beta1UpdateCloudExportRequest) (ImplResponse, error)
}
