/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudexportstub

type V202101beta1AwsProperties struct {
	Bucket string `json:"bucket,omitempty"`

	IamRoleArn string `json:"iamRoleArn,omitempty"`

	Region string `json:"region,omitempty"`

	DeleteAfterRead bool `json:"deleteAfterRead,omitempty"`

	MultipleBuckets bool `json:"multipleBuckets,omitempty"`
}
