/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudexportstub

type V202101beta1CloudExport struct {

	// The internal cloud export identifier. This is Read-only and assigned by Kentik.
	Id string `json:"id,omitempty"`

	Type V202101beta1CloudExportType `json:"type,omitempty"`

	// Whether this task is enabled and intended to run, or disabled.
	Enabled bool `json:"enabled,omitempty"`

	// A short name for this export.
	Name string `json:"name,omitempty"`

	// An optional, longer description.
	Description string `json:"description,omitempty"`

	ApiRoot *string `json:"apiRoot,omitempty"` // NOTE: updated by hand to pointer type

	FlowDest *string `json:"flowDest,omitempty"` // NOTE: updated by hand to pointer type

	// The identifier of the Kentik plan associated with this task.
	PlanId string `json:"planId,omitempty"`

	CloudProvider string `json:"cloudProvider,omitempty"`

	Aws *V202101beta1AwsProperties `json:"aws,omitempty"` // NOTE: updated by hand to pointer type

	Azure *V202101beta1AzureProperties `json:"azure,omitempty"` // NOTE: updated by hand to pointer type

	Gce *V202101beta1GceProperties `json:"gce,omitempty"` // NOTE: updated by hand to pointer type

	Ibm *V202101beta1IbmProperties `json:"ibm,omitempty"` // NOTE: updated by hand to pointer type

	Bgp *V202101beta1BgpProperties `json:"bgp,omitempty"` // NOTE: updated by hand to pointer type

	CurrentStatus *CloudExportv202101beta1Status `json:"currentStatus,omitempty"` // NOTE: updated by hand to pointer type
}
