/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cloudexportstub

type ProtobufAny struct {
	TypeUrl string `json:"typeUrl,omitempty"`

	Value string `json:"value,omitempty"`
}
