/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	syntheticsstub "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	SyntheticsAdminServiceApiService := syntheticsstub.NewSyntheticsAdminServiceApiService()
	SyntheticsAdminServiceApiController := syntheticsstub.NewSyntheticsAdminServiceApiController(SyntheticsAdminServiceApiService)

	SyntheticsDataServiceApiService := syntheticsstub.NewSyntheticsDataServiceApiService()
	SyntheticsDataServiceApiController := syntheticsstub.NewSyntheticsDataServiceApiController(SyntheticsDataServiceApiService)

	router := syntheticsstub.NewRouter(SyntheticsAdminServiceApiController, SyntheticsDataServiceApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
