/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1PingTaskDefinition struct for V202101beta1PingTaskDefinition
type V202101beta1PingTaskDefinition struct {
	Target *string `json:"target,omitempty"`
	Period *int64  `json:"period,omitempty"`
	Expiry *int64  `json:"expiry,omitempty"`
	Count  *int64  `json:"count,omitempty"`
}

// NewV202101beta1PingTaskDefinition instantiates a new V202101beta1PingTaskDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1PingTaskDefinition() *V202101beta1PingTaskDefinition {
	this := V202101beta1PingTaskDefinition{}
	return &this
}

// NewV202101beta1PingTaskDefinitionWithDefaults instantiates a new V202101beta1PingTaskDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1PingTaskDefinitionWithDefaults() *V202101beta1PingTaskDefinition {
	this := V202101beta1PingTaskDefinition{}
	return &this
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *V202101beta1PingTaskDefinition) GetTarget() string {
	if o == nil || o.Target == nil {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PingTaskDefinition) GetTargetOk() (*string, bool) {
	if o == nil || o.Target == nil {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *V202101beta1PingTaskDefinition) HasTarget() bool {
	if o != nil && o.Target != nil {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *V202101beta1PingTaskDefinition) SetTarget(v string) {
	o.Target = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *V202101beta1PingTaskDefinition) GetPeriod() int64 {
	if o == nil || o.Period == nil {
		var ret int64
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PingTaskDefinition) GetPeriodOk() (*int64, bool) {
	if o == nil || o.Period == nil {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *V202101beta1PingTaskDefinition) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int64 and assigns it to the Period field.
func (o *V202101beta1PingTaskDefinition) SetPeriod(v int64) {
	o.Period = &v
}

// GetExpiry returns the Expiry field value if set, zero value otherwise.
func (o *V202101beta1PingTaskDefinition) GetExpiry() int64 {
	if o == nil || o.Expiry == nil {
		var ret int64
		return ret
	}
	return *o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PingTaskDefinition) GetExpiryOk() (*int64, bool) {
	if o == nil || o.Expiry == nil {
		return nil, false
	}
	return o.Expiry, true
}

// HasExpiry returns a boolean if a field has been set.
func (o *V202101beta1PingTaskDefinition) HasExpiry() bool {
	if o != nil && o.Expiry != nil {
		return true
	}

	return false
}

// SetExpiry gets a reference to the given int64 and assigns it to the Expiry field.
func (o *V202101beta1PingTaskDefinition) SetExpiry(v int64) {
	o.Expiry = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *V202101beta1PingTaskDefinition) GetCount() int64 {
	if o == nil || o.Count == nil {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1PingTaskDefinition) GetCountOk() (*int64, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *V202101beta1PingTaskDefinition) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *V202101beta1PingTaskDefinition) SetCount(v int64) {
	o.Count = &v
}

func (o V202101beta1PingTaskDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Target != nil {
		toSerialize["target"] = o.Target
	}
	if o.Period != nil {
		toSerialize["period"] = o.Period
	}
	if o.Expiry != nil {
		toSerialize["expiry"] = o.Expiry
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1PingTaskDefinition struct {
	value *V202101beta1PingTaskDefinition
	isSet bool
}

func (v NullableV202101beta1PingTaskDefinition) Get() *V202101beta1PingTaskDefinition {
	return v.value
}

func (v *NullableV202101beta1PingTaskDefinition) Set(val *V202101beta1PingTaskDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1PingTaskDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1PingTaskDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1PingTaskDefinition(val *V202101beta1PingTaskDefinition) *NullableV202101beta1PingTaskDefinition {
	return &NullableV202101beta1PingTaskDefinition{value: val, isSet: true}
}

func (v NullableV202101beta1PingTaskDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1PingTaskDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
