/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
	"fmt"
)

// V202101beta1DNSRecord the model 'V202101beta1DNSRecord'
type V202101beta1DNSRecord string

// List of v202101beta1DNSRecord
const (
	V202101BETA1DNSRECORD_UNSPECIFIED V202101beta1DNSRecord = "DNS_RECORD_UNSPECIFIED"
	V202101BETA1DNSRECORD_A           V202101beta1DNSRecord = "DNS_RECORD_A"
	V202101BETA1DNSRECORD_AAAA        V202101beta1DNSRecord = "DNS_RECORD_AAAA"
	V202101BETA1DNSRECORD_CNAME       V202101beta1DNSRecord = "DNS_RECORD_CNAME"
	V202101BETA1DNSRECORD_DNAME       V202101beta1DNSRecord = "DNS_RECORD_DNAME"
	V202101BETA1DNSRECORD_NS          V202101beta1DNSRecord = "DNS_RECORD_NS"
	V202101BETA1DNSRECORD_MX          V202101beta1DNSRecord = "DNS_RECORD_MX"
	V202101BETA1DNSRECORD_PTR         V202101beta1DNSRecord = "DNS_RECORD_PTR"
	V202101BETA1DNSRECORD_SOA         V202101beta1DNSRecord = "DNS_RECORD_SOA"
)

var allowedV202101beta1DNSRecordEnumValues = []V202101beta1DNSRecord{
	"DNS_RECORD_UNSPECIFIED",
	"DNS_RECORD_A",
	"DNS_RECORD_AAAA",
	"DNS_RECORD_CNAME",
	"DNS_RECORD_DNAME",
	"DNS_RECORD_NS",
	"DNS_RECORD_MX",
	"DNS_RECORD_PTR",
	"DNS_RECORD_SOA",
}

func (v *V202101beta1DNSRecord) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V202101beta1DNSRecord(value)
	for _, existing := range allowedV202101beta1DNSRecordEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V202101beta1DNSRecord", value)
}

// NewV202101beta1DNSRecordFromValue returns a pointer to a valid V202101beta1DNSRecord
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV202101beta1DNSRecordFromValue(v string) (*V202101beta1DNSRecord, error) {
	ev := V202101beta1DNSRecord(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V202101beta1DNSRecord: valid values are %v", v, allowedV202101beta1DNSRecordEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V202101beta1DNSRecord) IsValid() bool {
	for _, existing := range allowedV202101beta1DNSRecordEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v202101beta1DNSRecord value
func (v V202101beta1DNSRecord) Ptr() *V202101beta1DNSRecord {
	return &v
}

type NullableV202101beta1DNSRecord struct {
	value *V202101beta1DNSRecord
	isSet bool
}

func (v NullableV202101beta1DNSRecord) Get() *V202101beta1DNSRecord {
	return v.value
}

func (v *NullableV202101beta1DNSRecord) Set(val *V202101beta1DNSRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1DNSRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1DNSRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1DNSRecord(val *V202101beta1DNSRecord) *NullableV202101beta1DNSRecord {
	return &NullableV202101beta1DNSRecord{value: val, isSet: true}
}

func (v NullableV202101beta1DNSRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1DNSRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
