/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1GridTest struct for V202101beta1GridTest
type V202101beta1GridTest struct {
	Targets *[]string `json:"targets,omitempty"`
}

// NewV202101beta1GridTest instantiates a new V202101beta1GridTest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1GridTest() *V202101beta1GridTest {
	this := V202101beta1GridTest{}
	return &this
}

// NewV202101beta1GridTestWithDefaults instantiates a new V202101beta1GridTest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1GridTestWithDefaults() *V202101beta1GridTest {
	this := V202101beta1GridTest{}
	return &this
}

// GetTargets returns the Targets field value if set, zero value otherwise.
func (o *V202101beta1GridTest) GetTargets() []string {
	if o == nil || o.Targets == nil {
		var ret []string
		return ret
	}
	return *o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GridTest) GetTargetsOk() (*[]string, bool) {
	if o == nil || o.Targets == nil {
		return nil, false
	}
	return o.Targets, true
}

// HasTargets returns a boolean if a field has been set.
func (o *V202101beta1GridTest) HasTargets() bool {
	if o != nil && o.Targets != nil {
		return true
	}

	return false
}

// SetTargets gets a reference to the given []string and assigns it to the Targets field.
func (o *V202101beta1GridTest) SetTargets(v []string) {
	o.Targets = &v
}

func (o V202101beta1GridTest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Targets != nil {
		toSerialize["targets"] = o.Targets
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1GridTest struct {
	value *V202101beta1GridTest
	isSet bool
}

func (v NullableV202101beta1GridTest) Get() *V202101beta1GridTest {
	return v.value
}

func (v *NullableV202101beta1GridTest) Set(val *V202101beta1GridTest) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1GridTest) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1GridTest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1GridTest(val *V202101beta1GridTest) *NullableV202101beta1GridTest {
	return &NullableV202101beta1GridTest{value: val, isSet: true}
}

func (v NullableV202101beta1GridTest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1GridTest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
