/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
	"time"
)

// V202101beta1GetTraceForTestRequest struct for V202101beta1GetTraceForTestRequest
type V202101beta1GetTraceForTestRequest struct {
	Id *string `json:"id,omitempty"`
	// Start of the time interval for this query.
	StartTime *time.Time `json:"startTime,omitempty"`
	// End of the time interval for this query.
	EndTime   *time.Time `json:"endTime,omitempty"`
	AgentIds  *[]string  `json:"agentIds,omitempty"`
	TargetIps *[]string  `json:"targetIps,omitempty"`
}

// NewV202101beta1GetTraceForTestRequest instantiates a new V202101beta1GetTraceForTestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1GetTraceForTestRequest() *V202101beta1GetTraceForTestRequest {
	this := V202101beta1GetTraceForTestRequest{}
	return &this
}

// NewV202101beta1GetTraceForTestRequestWithDefaults instantiates a new V202101beta1GetTraceForTestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1GetTraceForTestRequestWithDefaults() *V202101beta1GetTraceForTestRequest {
	this := V202101beta1GetTraceForTestRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1GetTraceForTestRequest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetTraceForTestRequest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1GetTraceForTestRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1GetTraceForTestRequest) SetId(v string) {
	o.Id = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *V202101beta1GetTraceForTestRequest) GetStartTime() time.Time {
	if o == nil || o.StartTime == nil {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetTraceForTestRequest) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *V202101beta1GetTraceForTestRequest) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *V202101beta1GetTraceForTestRequest) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *V202101beta1GetTraceForTestRequest) GetEndTime() time.Time {
	if o == nil || o.EndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetTraceForTestRequest) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || o.EndTime == nil {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *V202101beta1GetTraceForTestRequest) HasEndTime() bool {
	if o != nil && o.EndTime != nil {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *V202101beta1GetTraceForTestRequest) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetAgentIds returns the AgentIds field value if set, zero value otherwise.
func (o *V202101beta1GetTraceForTestRequest) GetAgentIds() []string {
	if o == nil || o.AgentIds == nil {
		var ret []string
		return ret
	}
	return *o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetTraceForTestRequest) GetAgentIdsOk() (*[]string, bool) {
	if o == nil || o.AgentIds == nil {
		return nil, false
	}
	return o.AgentIds, true
}

// HasAgentIds returns a boolean if a field has been set.
func (o *V202101beta1GetTraceForTestRequest) HasAgentIds() bool {
	if o != nil && o.AgentIds != nil {
		return true
	}

	return false
}

// SetAgentIds gets a reference to the given []string and assigns it to the AgentIds field.
func (o *V202101beta1GetTraceForTestRequest) SetAgentIds(v []string) {
	o.AgentIds = &v
}

// GetTargetIps returns the TargetIps field value if set, zero value otherwise.
func (o *V202101beta1GetTraceForTestRequest) GetTargetIps() []string {
	if o == nil || o.TargetIps == nil {
		var ret []string
		return ret
	}
	return *o.TargetIps
}

// GetTargetIpsOk returns a tuple with the TargetIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetTraceForTestRequest) GetTargetIpsOk() (*[]string, bool) {
	if o == nil || o.TargetIps == nil {
		return nil, false
	}
	return o.TargetIps, true
}

// HasTargetIps returns a boolean if a field has been set.
func (o *V202101beta1GetTraceForTestRequest) HasTargetIps() bool {
	if o != nil && o.TargetIps != nil {
		return true
	}

	return false
}

// SetTargetIps gets a reference to the given []string and assigns it to the TargetIps field.
func (o *V202101beta1GetTraceForTestRequest) SetTargetIps(v []string) {
	o.TargetIps = &v
}

func (o V202101beta1GetTraceForTestRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.EndTime != nil {
		toSerialize["endTime"] = o.EndTime
	}
	if o.AgentIds != nil {
		toSerialize["agentIds"] = o.AgentIds
	}
	if o.TargetIps != nil {
		toSerialize["targetIps"] = o.TargetIps
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1GetTraceForTestRequest struct {
	value *V202101beta1GetTraceForTestRequest
	isSet bool
}

func (v NullableV202101beta1GetTraceForTestRequest) Get() *V202101beta1GetTraceForTestRequest {
	return v.value
}

func (v *NullableV202101beta1GetTraceForTestRequest) Set(val *V202101beta1GetTraceForTestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1GetTraceForTestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1GetTraceForTestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1GetTraceForTestRequest(val *V202101beta1GetTraceForTestRequest) *NullableV202101beta1GetTraceForTestRequest {
	return &NullableV202101beta1GetTraceForTestRequest{value: val, isSet: true}
}

func (v NullableV202101beta1GetTraceForTestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1GetTraceForTestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
