/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1GetAgentResponse struct for V202101beta1GetAgentResponse
type V202101beta1GetAgentResponse struct {
	Agent *V202101beta1Agent `json:"agent,omitempty"`
}

// NewV202101beta1GetAgentResponse instantiates a new V202101beta1GetAgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1GetAgentResponse() *V202101beta1GetAgentResponse {
	this := V202101beta1GetAgentResponse{}
	return &this
}

// NewV202101beta1GetAgentResponseWithDefaults instantiates a new V202101beta1GetAgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1GetAgentResponseWithDefaults() *V202101beta1GetAgentResponse {
	this := V202101beta1GetAgentResponse{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *V202101beta1GetAgentResponse) GetAgent() V202101beta1Agent {
	if o == nil || o.Agent == nil {
		var ret V202101beta1Agent
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1GetAgentResponse) GetAgentOk() (*V202101beta1Agent, bool) {
	if o == nil || o.Agent == nil {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *V202101beta1GetAgentResponse) HasAgent() bool {
	if o != nil && o.Agent != nil {
		return true
	}

	return false
}

// SetAgent gets a reference to the given V202101beta1Agent and assigns it to the Agent field.
func (o *V202101beta1GetAgentResponse) SetAgent(v V202101beta1Agent) {
	o.Agent = &v
}

func (o V202101beta1GetAgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agent != nil {
		toSerialize["agent"] = o.Agent
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1GetAgentResponse struct {
	value *V202101beta1GetAgentResponse
	isSet bool
}

func (v NullableV202101beta1GetAgentResponse) Get() *V202101beta1GetAgentResponse {
	return v.value
}

func (v *NullableV202101beta1GetAgentResponse) Set(val *V202101beta1GetAgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1GetAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1GetAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1GetAgentResponse(val *V202101beta1GetAgentResponse) *NullableV202101beta1GetAgentResponse {
	return &NullableV202101beta1GetAgentResponse{value: val, isSet: true}
}

func (v NullableV202101beta1GetAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1GetAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
