/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1ListAgentsResponse struct for V202101beta1ListAgentsResponse
type V202101beta1ListAgentsResponse struct {
	Agents             *[]V202101beta1Agent `json:"agents,omitempty"`
	InvalidAgentsCount *int64               `json:"invalidAgentsCount,omitempty"`
}

// NewV202101beta1ListAgentsResponse instantiates a new V202101beta1ListAgentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1ListAgentsResponse() *V202101beta1ListAgentsResponse {
	this := V202101beta1ListAgentsResponse{}
	return &this
}

// NewV202101beta1ListAgentsResponseWithDefaults instantiates a new V202101beta1ListAgentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1ListAgentsResponseWithDefaults() *V202101beta1ListAgentsResponse {
	this := V202101beta1ListAgentsResponse{}
	return &this
}

// GetAgents returns the Agents field value if set, zero value otherwise.
func (o *V202101beta1ListAgentsResponse) GetAgents() []V202101beta1Agent {
	if o == nil || o.Agents == nil {
		var ret []V202101beta1Agent
		return ret
	}
	return *o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1ListAgentsResponse) GetAgentsOk() (*[]V202101beta1Agent, bool) {
	if o == nil || o.Agents == nil {
		return nil, false
	}
	return o.Agents, true
}

// HasAgents returns a boolean if a field has been set.
func (o *V202101beta1ListAgentsResponse) HasAgents() bool {
	if o != nil && o.Agents != nil {
		return true
	}

	return false
}

// SetAgents gets a reference to the given []V202101beta1Agent and assigns it to the Agents field.
func (o *V202101beta1ListAgentsResponse) SetAgents(v []V202101beta1Agent) {
	o.Agents = &v
}

// GetInvalidAgentsCount returns the InvalidAgentsCount field value if set, zero value otherwise.
func (o *V202101beta1ListAgentsResponse) GetInvalidAgentsCount() int64 {
	if o == nil || o.InvalidAgentsCount == nil {
		var ret int64
		return ret
	}
	return *o.InvalidAgentsCount
}

// GetInvalidAgentsCountOk returns a tuple with the InvalidAgentsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1ListAgentsResponse) GetInvalidAgentsCountOk() (*int64, bool) {
	if o == nil || o.InvalidAgentsCount == nil {
		return nil, false
	}
	return o.InvalidAgentsCount, true
}

// HasInvalidAgentsCount returns a boolean if a field has been set.
func (o *V202101beta1ListAgentsResponse) HasInvalidAgentsCount() bool {
	if o != nil && o.InvalidAgentsCount != nil {
		return true
	}

	return false
}

// SetInvalidAgentsCount gets a reference to the given int64 and assigns it to the InvalidAgentsCount field.
func (o *V202101beta1ListAgentsResponse) SetInvalidAgentsCount(v int64) {
	o.InvalidAgentsCount = &v
}

func (o V202101beta1ListAgentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agents != nil {
		toSerialize["agents"] = o.Agents
	}
	if o.InvalidAgentsCount != nil {
		toSerialize["invalidAgentsCount"] = o.InvalidAgentsCount
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1ListAgentsResponse struct {
	value *V202101beta1ListAgentsResponse
	isSet bool
}

func (v NullableV202101beta1ListAgentsResponse) Get() *V202101beta1ListAgentsResponse {
	return v.value
}

func (v *NullableV202101beta1ListAgentsResponse) Set(val *V202101beta1ListAgentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1ListAgentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1ListAgentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1ListAgentsResponse(val *V202101beta1ListAgentsResponse) *NullableV202101beta1ListAgentsResponse {
	return &NullableV202101beta1ListAgentsResponse{value: val, isSet: true}
}

func (v NullableV202101beta1ListAgentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1ListAgentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
