/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1UrlTest struct for V202101beta1UrlTest
type V202101beta1UrlTest struct {
	Target *string `json:"target,omitempty"`
}

// NewV202101beta1UrlTest instantiates a new V202101beta1UrlTest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1UrlTest() *V202101beta1UrlTest {
	this := V202101beta1UrlTest{}
	return &this
}

// NewV202101beta1UrlTestWithDefaults instantiates a new V202101beta1UrlTest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1UrlTestWithDefaults() *V202101beta1UrlTest {
	this := V202101beta1UrlTest{}
	return &this
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *V202101beta1UrlTest) GetTarget() string {
	if o == nil || o.Target == nil {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1UrlTest) GetTargetOk() (*string, bool) {
	if o == nil || o.Target == nil {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *V202101beta1UrlTest) HasTarget() bool {
	if o != nil && o.Target != nil {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *V202101beta1UrlTest) SetTarget(v string) {
	o.Target = &v
}

func (o V202101beta1UrlTest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Target != nil {
		toSerialize["target"] = o.Target
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1UrlTest struct {
	value *V202101beta1UrlTest
	isSet bool
}

func (v NullableV202101beta1UrlTest) Get() *V202101beta1UrlTest {
	return v.value
}

func (v *NullableV202101beta1UrlTest) Set(val *V202101beta1UrlTest) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1UrlTest) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1UrlTest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1UrlTest(val *V202101beta1UrlTest) *NullableV202101beta1UrlTest {
	return &NullableV202101beta1UrlTest{value: val, isSet: true}
}

func (v NullableV202101beta1UrlTest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1UrlTest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
