/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synthetics

import (
	"encoding/json"
)

// V202101beta1IDByIP struct for V202101beta1IDByIP
type V202101beta1IDByIP struct {
	Id *string `json:"id,omitempty"`
	Ip *string `json:"ip,omitempty"`
}

// NewV202101beta1IDByIP instantiates a new V202101beta1IDByIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1IDByIP() *V202101beta1IDByIP {
	this := V202101beta1IDByIP{}
	return &this
}

// NewV202101beta1IDByIPWithDefaults instantiates a new V202101beta1IDByIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1IDByIPWithDefaults() *V202101beta1IDByIP {
	this := V202101beta1IDByIP{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1IDByIP) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1IDByIP) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1IDByIP) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1IDByIP) SetId(v string) {
	o.Id = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *V202101beta1IDByIP) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1IDByIP) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *V202101beta1IDByIP) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *V202101beta1IDByIP) SetIp(v string) {
	o.Ip = &v
}

func (o V202101beta1IDByIP) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1IDByIP struct {
	value *V202101beta1IDByIP
	isSet bool
}

func (v NullableV202101beta1IDByIP) Get() *V202101beta1IDByIP {
	return v.value
}

func (v *NullableV202101beta1IDByIP) Set(val *V202101beta1IDByIP) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1IDByIP) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1IDByIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1IDByIP(val *V202101beta1IDByIP) *NullableV202101beta1IDByIP {
	return &NullableV202101beta1IDByIP{value: val, isSet: true}
}

func (v NullableV202101beta1IDByIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1IDByIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
