/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TaskState string

// List of V202101beta1TaskState
const (
	UNSPECIFIED V202101beta1TaskState = "TASK_STATE_UNSPECIFIED"
	CREATED     V202101beta1TaskState = "TASK_STATE_CREATED"
	UPDATED     V202101beta1TaskState = "TASK_STATE_UPDATED"
	DELETED     V202101beta1TaskState = "TASK_STATE_DELETED"
)
