/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TestMonitoringSettings struct {
	ActivationGracePeriod string `json:"activationGracePeriod,omitempty"`

	ActivationTimeUnit string `json:"activationTimeUnit,omitempty"`

	ActivationTimeWindow string `json:"activationTimeWindow,omitempty"`

	ActivationTimes string `json:"activationTimes,omitempty"`

	NotificationChannels []string `json:"notificationChannels,omitempty"`
}
