/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TaskHealth struct {
	Task V202101beta1Task `json:"task,omitempty"`

	Agents []V202101beta1AgentHealth `json:"agents,omitempty"`

	OverallHealth V202101beta1Health `json:"overallHealth,omitempty"`

	TargetAgent V202101beta1Agent `json:"targetAgent,omitempty"`
}
