/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1PatchTestRequest struct {
	Test V202101beta1Test `json:"test,omitempty"`

	Mask string `json:"mask,omitempty"`
}
