/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TestSettings struct {
	Hostname V202101beta1HostnameTest `json:"hostname,omitempty"`

	Ip V202101beta1IpTest `json:"ip,omitempty"`

	Agent V202101beta1AgentTest `json:"agent,omitempty"`

	Flow V202101beta1FlowTest `json:"flow,omitempty"`

	Site V202101beta1SiteTest `json:"site,omitempty"`

	Tag V202101beta1TagTest `json:"tag,omitempty"`

	Dns V202101beta1DnsTest `json:"dns,omitempty"`

	Url V202101beta1UrlTest `json:"url,omitempty"`

	AgentIds []string `json:"agentIds,omitempty"`

	Period int64 `json:"period,omitempty"`

	Count int64 `json:"count,omitempty"`

	Expiry int64 `json:"expiry,omitempty"`

	Limit int64 `json:"limit,omitempty"`

	Tasks []string `json:"tasks,omitempty"`

	HealthSettings V202101beta1HealthSettings `json:"healthSettings,omitempty"`

	MonitoringSettings V202101beta1TestMonitoringSettings `json:"monitoringSettings,omitempty"`

	Ping V202101beta1TestPingSettings `json:"ping,omitempty"`

	Trace V202101beta1TestTraceSettings `json:"trace,omitempty"`

	Port int64 `json:"port,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Family V202101beta1IpFamily `json:"family,omitempty"`

	Servers []string `json:"servers,omitempty"`

	TargetType string `json:"targetType,omitempty"`

	TargetValue string `json:"targetValue,omitempty"`

	UseLocalIp bool `json:"useLocalIp,omitempty"`

	Reciprocal bool `json:"reciprocal,omitempty"`

	RollupLevel int64 `json:"rollupLevel,omitempty"`
}
