/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1GetTraceForTestResponse struct {
	IpInfo []V202101beta1IpInfo `json:"ipInfo,omitempty"`

	TraceRoutes []V202101beta1TracerouteResult `json:"traceRoutes,omitempty"`
}
