/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TestTraceSettings struct {
	Period float32 `json:"period,omitempty"`

	Count float32 `json:"count,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Port float32 `json:"port,omitempty"`

	Expiry float32 `json:"expiry,omitempty"`

	Limit float32 `json:"limit,omitempty"`
}
