/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

import (
	"time"
)

type V202101beta1HealthMoment struct {
	Time time.Time `json:"time,omitempty"`

	SrcIp string `json:"srcIp,omitempty"`

	DstIp string `json:"dstIp,omitempty"`

	PacketLoss int64 `json:"packetLoss,omitempty"`

	AvgLatency int64 `json:"avgLatency,omitempty"`

	AvgWeightedLatency int64 `json:"avgWeightedLatency,omitempty"`

	RollingAvgLatency int64 `json:"rollingAvgLatency,omitempty"`

	RollingStddevLatency int64 `json:"rollingStddevLatency,omitempty"`

	RollingAvgWeightedLatency int64 `json:"rollingAvgWeightedLatency,omitempty"`

	LatencyHealth string `json:"latencyHealth,omitempty"`

	PacketLossHealth string `json:"packetLossHealth,omitempty"`

	OverallHealth V202101beta1Health `json:"overallHealth,omitempty"`

	AvgJitter int64 `json:"avgJitter,omitempty"`

	RollingAvgJitter int64 `json:"rollingAvgJitter,omitempty"`

	RollingStdJitter int64 `json:"rollingStdJitter,omitempty"`

	JitterHealth string `json:"jitterHealth,omitempty"`

	Data string `json:"data,omitempty"`

	Size int64 `json:"size,omitempty"`

	Status int64 `json:"status,omitempty"`

	TaskType string `json:"taskType,omitempty"`
}
