/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1IpInfo struct {
	Ip string `json:"ip,omitempty"`

	Asn V202101beta1Asn `json:"asn,omitempty"`

	Geo V202101beta1Geo `json:"geo,omitempty"`

	Dns V202101beta1Dns `json:"dns,omitempty"`
}
