/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1Trace struct {
	Hops []V202101beta1TraceHop `json:"hops,omitempty"`

	Target string `json:"target,omitempty"`

	Ips []string `json:"ips,omitempty"`
}
