/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

import (
	"time"
)

type V202101beta1Agent struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Status V202101beta1AgentStatus `json:"status,omitempty"`

	Alias string `json:"alias,omitempty"`

	Type string `json:"type,omitempty"`

	Os string `json:"os,omitempty"`

	Ip string `json:"ip,omitempty"`

	Lat float64 `json:"lat,omitempty"`

	Long float64 `json:"long,omitempty"`

	LastAuthed time.Time `json:"lastAuthed,omitempty"`

	Family V202101beta1IpFamily `json:"family,omitempty"`

	Asn int64 `json:"asn,omitempty"`

	SiteId string `json:"siteId,omitempty"`

	Version string `json:"version,omitempty"`

	Challenge string `json:"challenge,omitempty"`

	City string `json:"city,omitempty"`

	Region string `json:"region,omitempty"`

	Country string `json:"country,omitempty"`

	TestIds []string `json:"testIds,omitempty"`

	LocalIp string `json:"localIp,omitempty"`
}
