/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TestStatus string

// List of V202101beta1TestStatus
const (
	UNSPECIFIED V202101beta1TestStatus = "TEST_STATUS_UNSPECIFIED"
	ACTIVE      V202101beta1TestStatus = "TEST_STATUS_ACTIVE"
	PAUSED      V202101beta1TestStatus = "TEST_STATUS_PAUSED"
	DELETED     V202101beta1TestStatus = "TEST_STATUS_DELETED"
)
