/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1AgentStatus string

// List of V202101beta1AgentStatus
const (
	V202101BETA1AGENTSTATUS_UNSPECIFIED V202101beta1AgentStatus = "AGENT_STATUS_UNSPECIFIED"
	V202101BETA1AGENTSTATUS_OK          V202101beta1AgentStatus = "AGENT_STATUS_OK"
	V202101BETA1AGENTSTATUS_WAIT        V202101beta1AgentStatus = "AGENT_STATUS_WAIT"
	V202101BETA1AGENTSTATUS_DELETED     V202101beta1AgentStatus = "AGENT_STATUS_DELETED"
)
