/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

import (
	"time"
)

type V202101beta1Health struct {
	Health string `json:"health,omitempty"`

	Time time.Time `json:"time,omitempty"`
}
