/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1IpFamily string

// List of V202101beta1IpFamily
const (
	V202101BETA1IPFAMILY_UNSPECIFIED V202101beta1IpFamily = "IP_FAMILY_UNSPECIFIED"
	V202101BETA1IPFAMILY_V4          V202101beta1IpFamily = "IP_FAMILY_V4"
	V202101BETA1IPFAMILY_V6          V202101beta1IpFamily = "IP_FAMILY_V6"
	V202101BETA1IPFAMILY_DUAL        V202101beta1IpFamily = "IP_FAMILY_DUAL"
)
