/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1Trace struct {
	AgentId string `json:"agentId,omitempty"`

	AgentIp string `json:"agentIp,omitempty"`

	TargetIp string `json:"targetIp,omitempty"`

	HopCount int32 `json:"hopCount,omitempty"`

	Probes []V202101beta1TraceProbe `json:"probes,omitempty"`
}
