/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1GetTraceForTestResponse struct {
	Lookups V202101beta1TracerouteLookup `json:"lookups,omitempty"`

	TraceRoutes []V202101beta1TracerouteResult `json:"traceRoutes,omitempty"`

	TraceRoutesInfo V202101beta1TracerouteInfo `json:"traceRoutesInfo,omitempty"`
}
