/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TracerouteLookup struct {
	AgentIdByIp []V202101beta1IdbyIp `json:"agentIdByIp,omitempty"`

	Agents []V202101beta1Agent `json:"agents,omitempty"`

	Asns []V202101beta1Asn `json:"asns,omitempty"`

	DeviceIdByIp []V202101beta1IdbyIp `json:"deviceIdByIp,omitempty"`

	SiteIdByIp []V202101beta1IdbyIp `json:"siteIdByIp,omitempty"`

	Ips []V202101beta1IpInfo `json:"ips,omitempty"`
}
