/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1Stats struct {
	Average int32 `json:"average,omitempty"`

	Max int32 `json:"max,omitempty"`

	Total int32 `json:"total,omitempty"`
}
