/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

import (
	"time"
)

type V202101beta1MeshMetrics struct {
	Time time.Time `json:"time,omitempty"`

	Latency V202101beta1MeshMetric `json:"latency,omitempty"`

	PacketLoss V202101beta1MeshMetric `json:"packetLoss,omitempty"`

	Jitter V202101beta1MeshMetric `json:"jitter,omitempty"`
}
