/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

import (
	"time"
)

type V202101beta1GetTraceForTestRequest struct {
	Id string `json:"id,omitempty"`

	// Start of the time interval for this query.
	StartTime time.Time `json:"startTime,omitempty"`

	// End of the time interval for this query.
	EndTime time.Time `json:"endTime,omitempty"`

	AgentIds []string `json:"agentIds,omitempty"`

	TargetIps []string `json:"targetIps,omitempty"`
}
