/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

// V202101beta1ImplementType : Agent impl type determines global vs private agent to use for specific test types.   - IMPLEMENT_TYPE_RUST: setup IP test against a NODE global agent will fail.  - IMPLEMENT_TYPE_NODE: setup a page load test against a RUST global agent will fail.
type V202101beta1ImplementType string

// List of V202101beta1ImplementType
const (
	V202101BETA1IMPLEMENTTYPE_UNSPECIFIED V202101beta1ImplementType = "IMPLEMENT_TYPE_UNSPECIFIED"
	V202101BETA1IMPLEMENTTYPE_RUST        V202101beta1ImplementType = "IMPLEMENT_TYPE_RUST"
	V202101BETA1IMPLEMENTTYPE_NODE        V202101beta1ImplementType = "IMPLEMENT_TYPE_NODE"
)
