/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1UserInfo struct {
	Id string `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	FullName string `json:"fullName,omitempty"`
}
