/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1TraceHop struct {
	Ttl int32 `json:"ttl,omitempty"`

	Ip string `json:"ip,omitempty"`

	Timeout bool `json:"timeout,omitempty"`

	Latency int32 `json:"latency,omitempty"`

	MinExpectedLatency int32 `json:"minExpectedLatency,omitempty"`

	Asn int32 `json:"asn,omitempty"`

	Site int32 `json:"site,omitempty"`

	Region int32 `json:"region,omitempty"`

	Target bool `json:"target,omitempty"`

	TraceEnd bool `json:"traceEnd,omitempty"`
}
