/*
 * Synthetics Monitoring API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101beta1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package syntheticsstub

type V202101beta1ListTestsResponse struct {
	Tests []V202101beta1Test `json:"tests,omitempty"`

	InvalidTestsCount int64 `json:"invalidTestsCount,omitempty"`
}
