/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	cloudexportstub "github.com/kentik/community_sdk_golang/apiv6/localhost_apiserver/go"
)

func main() {
	log.Printf("Server started")

	repo := cloudexportstub.NewCloudExportRepo("CloudExportStorage.json")
	CloudExportAdminServiceApiService := cloudexportstub.NewCloudExportAdminServiceApiService(repo)
	CloudExportAdminServiceApiController := cloudexportstub.NewCloudExportAdminServiceApiController(CloudExportAdminServiceApiService)

	router := cloudexportstub.NewRouter(CloudExportAdminServiceApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
