/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"log"
	"net/http"

	cloudexportstub "github.com/kentik/community_sdk_golang/apiv6/localhost_apiserver/go"
)

func main() {
	port, storageFilePath := readPortStorage()

	repo := cloudexportstub.NewCloudExportRepo(storageFilePath)
	CloudExportAdminServiceApiService := cloudexportstub.NewCloudExportAdminServiceApiService(repo)
	CloudExportAdminServiceApiController := cloudexportstub.NewCloudExportAdminServiceApiController(CloudExportAdminServiceApiService)

	router := cloudexportstub.NewRouter(CloudExportAdminServiceApiController)

	log.Printf("Server started, port %s, storage %s", port, storageFilePath)
	log.Fatal(http.ListenAndServe(port, router))
}

func readPortStorage() (port string, storage string) {
	flag.StringVar(&port, "port", ":8080", "Port number for the server to listen to")
	flag.StringVar(&storage, "storage", "CloudExportStorage.json", "JSON file path for the server to read and write the data to")
	flag.Parse()
	return
}
