/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"log"
	"net/http"

	cloudexportstub "github.com/kentik/community_sdk_golang/apiv6/localhost_apiserver/cloudexport/go"
)

func main() {
	address, storageFilePath := readAddressStorage()

	repo := cloudexportstub.NewCloudExportRepo(storageFilePath)
	CloudExportAdminServiceApiService := cloudexportstub.NewCloudExportAdminServiceApiService(repo)
	CloudExportAdminServiceApiController := cloudexportstub.NewCloudExportAdminServiceApiController(CloudExportAdminServiceApiService)

	router := cloudexportstub.NewRouter(CloudExportAdminServiceApiController)

	log.Printf("Server started, address %s, storage %s", address, storageFilePath)
	log.Fatal(http.ListenAndServe(address, router))
}

func readAddressStorage() (address string, storage string) {
	flag.StringVar(&address, "addr", ":8080", "Address for the server to listen on")
	flag.StringVar(&storage, "storage", "CloudExportStorage.json", "JSON file path for the server to read and write the data to")
	flag.Parse()
	return
}
