/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudexport

import (
	"encoding/json"
)

// V202101beta1CloudExport struct for V202101beta1CloudExport
type V202101beta1CloudExport struct {
	// The internal cloud export identifier. This is Read-only and assigned by Kentik.
	Id   *string                      `json:"id,omitempty"`
	Type *V202101beta1CloudExportType `json:"type,omitempty"`
	// Whether this task is enabled and intended to run, or disabled.
	Enabled *bool `json:"enabled,omitempty"`
	// A short name for this export.
	Name *string `json:"name,omitempty"`
	// An optional, longer description.
	Description *string `json:"description,omitempty"`
	ApiRoot     *string `json:"apiRoot,omitempty"`
	FlowDest    *string `json:"flowDest,omitempty"`
	// The identifier of the Kentik plan associated with this task.
	PlanId        *string                        `json:"planId,omitempty"`
	CloudProvider *string                        `json:"cloudProvider,omitempty"`
	Aws           *V202101beta1AwsProperties     `json:"aws,omitempty"`
	Azure         *V202101beta1AzureProperties   `json:"azure,omitempty"`
	Gce           *V202101beta1GceProperties     `json:"gce,omitempty"`
	Ibm           *V202101beta1IbmProperties     `json:"ibm,omitempty"`
	Bgp           *V202101beta1BgpProperties     `json:"bgp,omitempty"`
	CurrentStatus *CloudExportv202101beta1Status `json:"currentStatus,omitempty"`
}

// NewV202101beta1CloudExport instantiates a new V202101beta1CloudExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1CloudExport() *V202101beta1CloudExport {
	this := V202101beta1CloudExport{}
	var type_ V202101beta1CloudExportType = UNSPECIFIED
	this.Type = &type_
	return &this
}

// NewV202101beta1CloudExportWithDefaults instantiates a new V202101beta1CloudExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1CloudExportWithDefaults() *V202101beta1CloudExport {
	this := V202101beta1CloudExport{}
	var type_ V202101beta1CloudExportType = UNSPECIFIED
	this.Type = &type_
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V202101beta1CloudExport) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetType() V202101beta1CloudExportType {
	if o == nil || o.Type == nil {
		var ret V202101beta1CloudExportType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetTypeOk() (*V202101beta1CloudExportType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given V202101beta1CloudExportType and assigns it to the Type field.
func (o *V202101beta1CloudExport) SetType(v V202101beta1CloudExportType) {
	o.Type = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *V202101beta1CloudExport) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V202101beta1CloudExport) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V202101beta1CloudExport) SetDescription(v string) {
	o.Description = &v
}

// GetApiRoot returns the ApiRoot field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetApiRoot() string {
	if o == nil || o.ApiRoot == nil {
		var ret string
		return ret
	}
	return *o.ApiRoot
}

// GetApiRootOk returns a tuple with the ApiRoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetApiRootOk() (*string, bool) {
	if o == nil || o.ApiRoot == nil {
		return nil, false
	}
	return o.ApiRoot, true
}

// HasApiRoot returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasApiRoot() bool {
	if o != nil && o.ApiRoot != nil {
		return true
	}

	return false
}

// SetApiRoot gets a reference to the given string and assigns it to the ApiRoot field.
func (o *V202101beta1CloudExport) SetApiRoot(v string) {
	o.ApiRoot = &v
}

// GetFlowDest returns the FlowDest field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetFlowDest() string {
	if o == nil || o.FlowDest == nil {
		var ret string
		return ret
	}
	return *o.FlowDest
}

// GetFlowDestOk returns a tuple with the FlowDest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetFlowDestOk() (*string, bool) {
	if o == nil || o.FlowDest == nil {
		return nil, false
	}
	return o.FlowDest, true
}

// HasFlowDest returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasFlowDest() bool {
	if o != nil && o.FlowDest != nil {
		return true
	}

	return false
}

// SetFlowDest gets a reference to the given string and assigns it to the FlowDest field.
func (o *V202101beta1CloudExport) SetFlowDest(v string) {
	o.FlowDest = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetPlanId() string {
	if o == nil || o.PlanId == nil {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetPlanIdOk() (*string, bool) {
	if o == nil || o.PlanId == nil {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasPlanId() bool {
	if o != nil && o.PlanId != nil {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *V202101beta1CloudExport) SetPlanId(v string) {
	o.PlanId = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetCloudProvider() string {
	if o == nil || o.CloudProvider == nil {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetCloudProviderOk() (*string, bool) {
	if o == nil || o.CloudProvider == nil {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasCloudProvider() bool {
	if o != nil && o.CloudProvider != nil {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *V202101beta1CloudExport) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetAws returns the Aws field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetAws() V202101beta1AwsProperties {
	if o == nil || o.Aws == nil {
		var ret V202101beta1AwsProperties
		return ret
	}
	return *o.Aws
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetAwsOk() (*V202101beta1AwsProperties, bool) {
	if o == nil || o.Aws == nil {
		return nil, false
	}
	return o.Aws, true
}

// HasAws returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasAws() bool {
	if o != nil && o.Aws != nil {
		return true
	}

	return false
}

// SetAws gets a reference to the given V202101beta1AwsProperties and assigns it to the Aws field.
func (o *V202101beta1CloudExport) SetAws(v V202101beta1AwsProperties) {
	o.Aws = &v
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetAzure() V202101beta1AzureProperties {
	if o == nil || o.Azure == nil {
		var ret V202101beta1AzureProperties
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetAzureOk() (*V202101beta1AzureProperties, bool) {
	if o == nil || o.Azure == nil {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasAzure() bool {
	if o != nil && o.Azure != nil {
		return true
	}

	return false
}

// SetAzure gets a reference to the given V202101beta1AzureProperties and assigns it to the Azure field.
func (o *V202101beta1CloudExport) SetAzure(v V202101beta1AzureProperties) {
	o.Azure = &v
}

// GetGce returns the Gce field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetGce() V202101beta1GceProperties {
	if o == nil || o.Gce == nil {
		var ret V202101beta1GceProperties
		return ret
	}
	return *o.Gce
}

// GetGceOk returns a tuple with the Gce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetGceOk() (*V202101beta1GceProperties, bool) {
	if o == nil || o.Gce == nil {
		return nil, false
	}
	return o.Gce, true
}

// HasGce returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasGce() bool {
	if o != nil && o.Gce != nil {
		return true
	}

	return false
}

// SetGce gets a reference to the given V202101beta1GceProperties and assigns it to the Gce field.
func (o *V202101beta1CloudExport) SetGce(v V202101beta1GceProperties) {
	o.Gce = &v
}

// GetIbm returns the Ibm field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetIbm() V202101beta1IbmProperties {
	if o == nil || o.Ibm == nil {
		var ret V202101beta1IbmProperties
		return ret
	}
	return *o.Ibm
}

// GetIbmOk returns a tuple with the Ibm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetIbmOk() (*V202101beta1IbmProperties, bool) {
	if o == nil || o.Ibm == nil {
		return nil, false
	}
	return o.Ibm, true
}

// HasIbm returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasIbm() bool {
	if o != nil && o.Ibm != nil {
		return true
	}

	return false
}

// SetIbm gets a reference to the given V202101beta1IbmProperties and assigns it to the Ibm field.
func (o *V202101beta1CloudExport) SetIbm(v V202101beta1IbmProperties) {
	o.Ibm = &v
}

// GetBgp returns the Bgp field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetBgp() V202101beta1BgpProperties {
	if o == nil || o.Bgp == nil {
		var ret V202101beta1BgpProperties
		return ret
	}
	return *o.Bgp
}

// GetBgpOk returns a tuple with the Bgp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetBgpOk() (*V202101beta1BgpProperties, bool) {
	if o == nil || o.Bgp == nil {
		return nil, false
	}
	return o.Bgp, true
}

// HasBgp returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasBgp() bool {
	if o != nil && o.Bgp != nil {
		return true
	}

	return false
}

// SetBgp gets a reference to the given V202101beta1BgpProperties and assigns it to the Bgp field.
func (o *V202101beta1CloudExport) SetBgp(v V202101beta1BgpProperties) {
	o.Bgp = &v
}

// GetCurrentStatus returns the CurrentStatus field value if set, zero value otherwise.
func (o *V202101beta1CloudExport) GetCurrentStatus() CloudExportv202101beta1Status {
	if o == nil || o.CurrentStatus == nil {
		var ret CloudExportv202101beta1Status
		return ret
	}
	return *o.CurrentStatus
}

// GetCurrentStatusOk returns a tuple with the CurrentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1CloudExport) GetCurrentStatusOk() (*CloudExportv202101beta1Status, bool) {
	if o == nil || o.CurrentStatus == nil {
		return nil, false
	}
	return o.CurrentStatus, true
}

// HasCurrentStatus returns a boolean if a field has been set.
func (o *V202101beta1CloudExport) HasCurrentStatus() bool {
	if o != nil && o.CurrentStatus != nil {
		return true
	}

	return false
}

// SetCurrentStatus gets a reference to the given CloudExportv202101beta1Status and assigns it to the CurrentStatus field.
func (o *V202101beta1CloudExport) SetCurrentStatus(v CloudExportv202101beta1Status) {
	o.CurrentStatus = &v
}

func (o V202101beta1CloudExport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.ApiRoot != nil {
		toSerialize["apiRoot"] = o.ApiRoot
	}
	if o.FlowDest != nil {
		toSerialize["flowDest"] = o.FlowDest
	}
	if o.PlanId != nil {
		toSerialize["planId"] = o.PlanId
	}
	if o.CloudProvider != nil {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if o.Aws != nil {
		toSerialize["aws"] = o.Aws
	}
	if o.Azure != nil {
		toSerialize["azure"] = o.Azure
	}
	if o.Gce != nil {
		toSerialize["gce"] = o.Gce
	}
	if o.Ibm != nil {
		toSerialize["ibm"] = o.Ibm
	}
	if o.Bgp != nil {
		toSerialize["bgp"] = o.Bgp
	}
	if o.CurrentStatus != nil {
		toSerialize["currentStatus"] = o.CurrentStatus
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1CloudExport struct {
	value *V202101beta1CloudExport
	isSet bool
}

func (v NullableV202101beta1CloudExport) Get() *V202101beta1CloudExport {
	return v.value
}

func (v *NullableV202101beta1CloudExport) Set(val *V202101beta1CloudExport) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1CloudExport) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1CloudExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1CloudExport(val *V202101beta1CloudExport) *NullableV202101beta1CloudExport {
	return &NullableV202101beta1CloudExport{value: val, isSet: true}
}

func (v NullableV202101beta1CloudExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1CloudExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
