/*
 * Cloud Export Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 202101
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudexport

import (
	"encoding/json"
)

// V202101beta1UpdateCloudExportResponse struct for V202101beta1UpdateCloudExportResponse
type V202101beta1UpdateCloudExportResponse struct {
	Export *V202101beta1CloudExport `json:"export,omitempty"`
}

// NewV202101beta1UpdateCloudExportResponse instantiates a new V202101beta1UpdateCloudExportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV202101beta1UpdateCloudExportResponse() *V202101beta1UpdateCloudExportResponse {
	this := V202101beta1UpdateCloudExportResponse{}
	return &this
}

// NewV202101beta1UpdateCloudExportResponseWithDefaults instantiates a new V202101beta1UpdateCloudExportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV202101beta1UpdateCloudExportResponseWithDefaults() *V202101beta1UpdateCloudExportResponse {
	this := V202101beta1UpdateCloudExportResponse{}
	return &this
}

// GetExport returns the Export field value if set, zero value otherwise.
func (o *V202101beta1UpdateCloudExportResponse) GetExport() V202101beta1CloudExport {
	if o == nil || o.Export == nil {
		var ret V202101beta1CloudExport
		return ret
	}
	return *o.Export
}

// GetExportOk returns a tuple with the Export field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V202101beta1UpdateCloudExportResponse) GetExportOk() (*V202101beta1CloudExport, bool) {
	if o == nil || o.Export == nil {
		return nil, false
	}
	return o.Export, true
}

// HasExport returns a boolean if a field has been set.
func (o *V202101beta1UpdateCloudExportResponse) HasExport() bool {
	if o != nil && o.Export != nil {
		return true
	}

	return false
}

// SetExport gets a reference to the given V202101beta1CloudExport and assigns it to the Export field.
func (o *V202101beta1UpdateCloudExportResponse) SetExport(v V202101beta1CloudExport) {
	o.Export = &v
}

func (o V202101beta1UpdateCloudExportResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Export != nil {
		toSerialize["export"] = o.Export
	}
	return json.Marshal(toSerialize)
}

type NullableV202101beta1UpdateCloudExportResponse struct {
	value *V202101beta1UpdateCloudExportResponse
	isSet bool
}

func (v NullableV202101beta1UpdateCloudExportResponse) Get() *V202101beta1UpdateCloudExportResponse {
	return v.value
}

func (v *NullableV202101beta1UpdateCloudExportResponse) Set(val *V202101beta1UpdateCloudExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV202101beta1UpdateCloudExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV202101beta1UpdateCloudExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV202101beta1UpdateCloudExportResponse(val *V202101beta1UpdateCloudExportResponse) *NullableV202101beta1UpdateCloudExportResponse {
	return &NullableV202101beta1UpdateCloudExportResponse{value: val, isSet: true}
}

func (v NullableV202101beta1UpdateCloudExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV202101beta1UpdateCloudExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
